Feature/enumerable methods
oscarnava/enumerable-methods pull request #1
Opened 2019-08-20 20:57 UTC by oscarnava

For review

2019-08-20 22:04 UTC, maelfosso requested changes
Hello,

You write a really nice code. It was a pleasure to read it.
Please, check the comment below and make those changes.

Thanks.

2019-08-20 22:04 UTC, maelfosso commented on my_enumerable.rb
> +  end
Not working
```
> [nil, true, 99].all? 
 => false 
> [nil, true, 99].my_all? 
Traceback (most recent call last):
        7: from /usr/local/rvm/rubies/ruby-2.5.1/bin/irb:11:in `<main>'
        6: from (irb):14
        5: from my_enumerable.rb:28:in `my_all?'
        4: from my_enumerable.rb:6:in `my_each'
        3: from my_enumerable.rb:6:in `each'
        2: from my_enumerable.rb:7:in `block in my_each'
        1: from my_enumerable.rb:29:in `block in my_all?'
LocalJumpError (no block given (yield))
```

2019-08-20 22:04 UTC, maelfosso commented on my_enumerable.rb
> +  end
Not working 
```
> [nil, true, 99].any? 
 => true 
> [nil, true, 99].my_any? 
Traceback (most recent call last):
        7: from /usr/local/rvm/rubies/ruby-2.5.1/bin/irb:11:in `<main>'
        6: from (irb):22
        5: from my_enumerable.rb:35:in `my_any?'
        4: from my_enumerable.rb:6:in `my_each'
        3: from my_enumerable.rb:6:in `each'
        2: from my_enumerable.rb:7:in `block in my_each'
        1: from my_enumerable.rb:36:in `block in my_any?'
LocalJumpError (no block given (yield))
```

2019-08-20 22:04 UTC, maelfosso commented on my_enumerable.rb
> +  end
Not working 
```
> [nil, false, true].none?  
 => false 
> [nil, false, true].my_none?  
Traceback (most recent call last):
        8: from /usr/local/rvm/rubies/ruby-2.5.1/bin/irb:11:in `<main>'
        7: from (irb):33
        6: from my_enumerable.rb:42:in `my_none?'
        5: from my_enumerable.rb:35:in `my_any?'
        4: from my_enumerable.rb:6:in `my_each'
        3: from my_enumerable.rb:6:in `each'
        2: from my_enumerable.rb:7:in `block in my_each'
        1: from my_enumerable.rb:36:in `block in my_any?'
LocalJumpError (no block given (yield))
```

2019-08-21 00:12 UTC, oscarnava commented on my_enumerable.rb
> +  end
Solved problems, My bad :-(

2019-08-21 01:31 UTC, maelfosso approved these changes
# Good job :+1: 

You can merge your project and submit the project completion form.
Good luck with your next project.

2019-08-21 01:31 UTC, maelfosso commented on my_enumerable.rb
> +  end
:+1:

2019-08-21 01:31 UTC, maelfosso commented on my_enumerable.rb
> +  end
:+1:

2019-08-21 01:31 UTC, maelfosso commented on my_enumerable.rb
> +  end
:+1:

2019-08-21 02:31 UTC, merged